force-app/main/default/objects/complaint__c/complaint__c.object-meta.xml
<CustomObject>
    <label>complaint</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/complaint__c/fields/complaint__c.field-meta.xml
<CustomField>
    <fullName>complaint__c</fullName>
    <label>complaint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/complaints__c/complaints__c.object-meta.xml
<CustomObject>
    <label>complaints</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>complaintss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/past_history__c/past_history__c.object-meta.xml
<CustomObject>
    <label>past history</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>past historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/past_history__c/fields/pastHistory__c.field-meta.xml
<CustomField>
    <fullName>pastHistory__c</fullName>
    <label>pastHistory</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ref_by__c/ref_by__c.object-meta.xml
<CustomObject>
    <label>ref by</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ref bys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ref_by__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>firstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ref_by__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>lastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RefDocList.cls
public with sharing class RefDocList {
   //Refer Doctor tab logic start
    @AuraEnabled(cacheable=true)
    public static List<ref_by__c> refDocData(){
       return [SELECT Id, firstName__c, lastName__c FROM ref_by__c];
  }
    //Refer Doctor tab logic end

    //Past History tab logic start
  @AuraEnabled(cacheable=true)
    public static List<past_history__c> pastHis(){
       return [SELECT pastHistory__c FROM past_history__c];
  }
  //Past History tab logic end

  //Past Complaint tab logic start
  @AuraEnabled(cacheable=true)
    public static List<complaints__c> complaint(){
       return [SELECT complaint__c FROM complaints__c];
  }
  //Past Complaint tab logic end 
}